### ISSUE TITLE
No ptpimg account

### ISSUE THREAD

**Issue by rr2121** [TrackerTools/REDCamp#1]
I've almost got this running.  Thank you for this script

I am not 'lucky' enough to have a ptpimg account.  How should I modify the script to not fail  at
ral_links = transcode.make_spectrograms(release_dir, config.get('ptpimg', 'api_key'))
(and any other references to ptpimg)?

I've left my api key blank in the config file.

Is it possible to use imgur instead?

`INFO Generating Spectrograms
Traceback (most recent call last):
  File "redcamp.py", line 443, in <module>
    main()
  File "redcamp.py", line 358, in main
    spectral_links = transcode.make_spectrograms(release_dir, config.get('ptpimg', 'api_key'))
  File "~/redcamp/transcode.py", line 59, in make_spectrograms
    links = api.upload_files(*spectrals)
  File "~/Library/Python/3.8/lib/python/site-packages/ptpimg_uploader.py", line 84, in upload_files
    return self._perform(files=files)
  File "~/Library/Python/3.8/lib/python/site-packages/ptpimg_uploader.py", line 60, in _perform
    raise UploadFailed(
ptpimg_uploader.UploadFailed: Failed. Status 403:
b''`

**Comment by TrackerTools** [comment]
If you're on RED you should be able to register for a PTPImg account. It's not exclusive to PTP.

https://ptpimg.me/register.php

**Comment by rr2121** [comment]
I have tried registering twice with 2 different email accounts and I never receive an email verification link from them to open the account.  After registering and trying to login, it says I need to click the email verification link first - which I never get.  Apparently from reading on RED forum, this is a common problem with new accounts for a long time.

**Comment by rr2121** [comment]
If I could just disable the ptpimg uploading and do that manually with imgur so I can get by the errors in the script that would be great.

**Comment by TrackerTools** [comment]
I believe RED has an upload endpoint that uses their own ptpimg key. I will look at integrating that. In the meantime I'll try and add an alternative upload option.

**Comment by rr2121** [comment]
Thank you!  The BC scrape and download works great, but I just hit this bump with ptpimg.  It just requires some manual work at the end.  I'm not sure why they insist on using this image host when they are unresponsive for new users.  Thank you again.

**Comment by danofun** [comment]
same issue as @rr2121. Thanks for looking into adding an alternative upload option. [smoked-salmon](https://github.com/ligh7s/smoked-salmon) offers several choices including imgur. May be of use in the implementation.
